### ISSUE TITLE
Port the theme for Webstorm/IntelliJ Ideas

### ISSUE THREAD

**Issue by davioliveira-dev** [mao-santaella-rs/NightWolfTheme#40]
**Describe the solution you'd like**
Hi, I love your theme, and recently started using Webstorm and i'm missing your theme on Jetbrains's plugins.

It's possible do a port? Can i help?

**Comment by mao-santaella-rs** [comment]
Hi @davioliveira-dev thanks for the compliments, I don't really know how to make a theme for Webstorm, I made it for vscode because is the one I use every day and I didn't find anything I liked, if you want you can take the colors in the source code to make the Webstorm version no problem, let me know if you need me to explain to you how the colors work in the theme, this way. you'll have more understanding of how to create one based on these colors.

thanks again.
